### ISSUE TITLE
NameVirtualHost is deprecated in Apache 2.4.x

### ISSUE THREAD

**Issue by star-szr** [virtualhost/virtualhost.sh#70]
Partial output from `apachectl -t`:

```
AH00548: NameVirtualHost has no effect and will be removed in the next release
```

Ref. https://httpd.apache.org/docs/2.4/mod/core.html#namevirtualhost

So for backwards compatibility it's still needed, but we don't need it for OS X 10.10 and up.

**Comment by wimleers** [comment]
Anybody following the guide at https://www.getgrav.org/blog/macos-sierra-apache-multiple-php-versions will have Apache 2.4, and will hence see this whenever they restart Apache. Let's fix this? :)

**Comment by star-szr** [comment]
Hi @wimleers, fancy seeing you here :)

This has been an issue for a while, not new to Sierra (unless Sierra has a newer version of Apache that deprecates this harder?). I haven't been seeing the warning every time I restart Apache, only when checking syntax. I'm on 10.11 (El Capitan) though.

The code around [here](https://github.com/virtualhost/virtualhost.sh/blob/master/virtualhost.sh#L567) would need some reworking to work in a BC manner (we could check whether we're including the virtualhost directory rather than grepping for the NameVirtualHost line). We already have `$APACHE_VERSION` along with `$APACHE_MAJOR_VERSION` `$APACHE_MINOR_VERSION` `$APACHE_PATCH_VERSION` set for comparisons.

**Comment by star-szr** [comment]
There's a PR at #77, could use some eyes and testing.

**Comment by kitsguru** [comment]
Fixed in V2 beta1
